### ISSUE TITLE
Getting 404 while installing package

### ISSUE THREAD

**Issue by ritox842** [sass/node-sass-middleware#107]
Hello.

I'm trying to use node-sass-middleware in my new generated project (From WebStorm IDE) and I'm getting a 404 error on this package.
I even tried to install it manually but I got the same 404 error. 

The error I'm getting is attached in the following pic:
![image](https://user-images.githubusercontent.com/1297909/28230556-7e169132-68b5-11e7-906c-1a3d7cd93239.png)

How can I install this package?

**Comment by am11** [comment]
Hi, I am unable to reproduce it locally: `npm i node-sass-middleware` succeeds. Could be a network issue?

**Comment by nschonni** [comment]
You're running Node 8 and trying to install 3.13.1 of node-sass. Please upgrade to 4.5.3 node-sass if you want to run Node 8

**Comment by ritox842** [comment]
Thank you! 
Iv'e updated my node-sass and it helped me. Now the project is running.
