### ISSUE TITLE
Allow color to be disabled in default logger

### ISSUE THREAD

**Issue by nic-hartley** [sass/node-sass-middleware#117]
I came across an odd line in my logfile recently. While I don't have it anymore -- it didn't occur to me to save it before I cleaned it up -- I realized it was because the output was colorized.

This isn't a major issue by any means because we can always supply our own logging functions (that's what I did), but it is frustrating. It would be nice to have an option (roughly the same type as `debug`) to disable colors.

This could be as simple as adding a line into the initialization:

```javascript
let debugFormat = options.colorize ? "colorized format" : "non-colorized format";
```

and then changing the `console.log` and `console.error` in the default logging function to use `debugFormat` instead of a string.

(Semi-pseudocode because I can't currently test an actual fix, though tomorrow I'd be happy to make a pull request)

**Comment by nschonni** [comment]
node-sass uses Chalk, you can use their environment variables to disable if you want https://github.com/chalk/chalk/#chalksupportscolor
