### ISSUE TITLE
Publish release 0.12.0 to npm

### ISSUE THREAD

**Issue by carloscuesta** [sass/node-sass-middleware#124]
Hello!

All of this changes https://github.com/sass/node-sass-middleware/compare/v0.11.0...master hasn't been released and published to npm yet.

Thanks 🙏

**Comment by nschonni** [comment]
Most of that is formatting/test/documentation changes. The only functional change is a "beep" option

**Comment by carloscuesta** [comment]
@nschonni That's mostly true but this commit https://github.com/sass/node-sass-middleware/commit/9acd19fd527e29e6c58e98ed07b8b3d9dda72a30 makes a difference

Because it updates `node-sass` from `4.5.0` to `4.9.0` and that version supports Node.js `10.x`

**Comment by nschonni** [comment]
It already uses the `^` version range in package.json, so it is installing 4.12.0 right now, even without that commit. If you're seeing an older version it would be because of a lockfile or your npm cache

**Comment by carloscuesta** [comment]
Yes I'm aware of the `^` version range, just curious about what's the stopper for publishing this on npm, even though the only functional change it's a "beep" option.

Nevermind, thanks for the quick reply! 😊
