### ISSUE TITLE
Confusing documentation 

### ISSUE THREAD

**Issue by BenjaminCrozier** [sass/node-sass-middleware#125]
>indentedSyntax - [true | false], false by default. Compiles files with the .sass extension instead of .scss in the src directory.

should read 

>indentedSyntax - [true | false], false by default. **If true** compiles files with the .sass extension instead of .scss in the src directory.

**Comment by mgreter** [comment]
This is open source, so feel free to make Pull Request to improve docs!

**Comment by lillem4n** [comment]
Fixed here: https://github.com/sass/node-sass-middleware/pull/127

**Comment by BenjaminCrozier** [comment]
on behalf of all the easily confused dummies: ty.
