### ISSUE TITLE
Sass files not recompiling

### ISSUE THREAD

**Issue by krazyjakee** [sass/node-sass-middleware#13]
I am using nodemon to detect sass changes and restart the server, however, I have had to add extra functionality so that the server deletes the compiled css files in order that node-sass-middleware can compile them. If I leave the css files undeleted, they will not be updated. This is not a great workflow and ideally sass-middleware will just update the pre-existing css files.

My sass content is very simple, no special circumstances to report.

**Comment by am11** [comment]
Please reopen, if this is still an issue with v0.6.0.
