### ISSUE TITLE
Node v16 compatibility

### ISSUE THREAD

**Issue by sharov68** [sass/node-sass-middleware#148]
Hello guys!
Could you provide compatibility with node v16 ?
Thanks!

**Comment by woneob** [comment]
https://github.com/sass/node-sass-middleware/blob/b6a78e0b7824884ccf3c731cb113fb3ed5b5c411/package.json#L34
Compatibility for Node v16 was committed to master branch by @nschonni 7 month ago,  
but npm registry has not been updated yet.  
Please release and publish to npm

**Comment by BoredGameGeek** [comment]
I think this has been updated in npm (https://www.npmjs.com/package/node-sass-middleware) - can we close this issue?
