### ISSUE TITLE
how to watch the scss file?

### ISSUE THREAD

**Issue by janryWang** [sass/node-sass-middleware#21]
How to use the watch in the development ?

**Comment by mrmoses** [comment]
You can add the `force: true` option to always recompile during development.

**Comment by janryWang** [comment]
@mrmoses Thanks😄

**Comment by SeanBlader** [comment]
Holy crap I was looking for that for over an hour. That should probably be right in the example, or at least documented somewhere.

**Comment by keithamus** [comment]
@SeanBlader could you please send us a pull request for how you expect the documentation to be? If you find a gap you're the perfect person to fill it! If you need help let any of the contributors know and we'll help out.
