### ISSUE TITLE
If an imported file is not found request never ends

### ISSUE THREAD

**Issue by bumxu** [sass/node-sass-middleware#31]
If an imported file doesn't exist the site is not able to load the stylesheet and stays waiting indefinitely.
There are no notifications in console.

![image](https://www.google.com/tools/dlpage/res/chrome/images/chrome_throbber_fast_16.gif)

**Comment by Bumxu** [comment]
When **node-sass** fails, ```success``` is not called, so this code is not executed and load never ends.

```javascript
res.writeHead(200, {
	'Content-Type': 'text/css',
	'Cache-Control': 'max-age=0'
});
res.end(result.css);
```

Instead of that, **node-sass** calls [```error```](https://github.com/sass/node-sass#error).
I'm thinking of supporting the **node-sass** ```error``` block and improve debug mode killing #22 in the way.

**Comment by am11** [comment]
Great work @Bumxu. :+1: 
Actually node-sass-middleware haven't been updated in a while to catchup with changes made in node-sass.

The generic syntax is in v2.0.1 is:

```javascript
var options = {
  data: 's { a: ss }',
  file: 'path/to/my.scss',
  success: function(result) { },
  error: function(err) { }
};

require('node-sass').render(options);
```

Starting with v2.1, the above syntax will work but deprecated in favour of node style callbacks:

```javascript
var options = {
  data: 's { a: ss }',
  file: 'path/to/my.scss'
};

require('node-sass').render(options, function(err, result) { });
```

**Comment by Bumxu** [comment]
Good approach!

So better wait for 2.1...

Thanks :)

**Comment by xandorxicay** [comment]
this would be good to commit I have the same issue when I use ```@import```

**Comment by adamkdean** [comment]
I would also like this

**Comment by bumxu** [comment]
And.... node-sass v3 is here! :D
Can we already play with this?

**Comment by am11** [comment]
Yup, but couple of major changes would need to be made (as v3 has most breaking changes made till date).

I will see if I get time to pull it off over the weekend. Otherwise, anyone can start a PR (/cc @iMoritz @jerone) and I will help knitting all pieces together. node-sass Readme and v3-alpha to v3-stable (https://github.com/sass/node-sass/releases/tag/v3.0.0) docs would most probably help in upgrade process. For reference, see the v2-v3 upgrade diff for grunt-sass: https://github.com/sindresorhus/grunt-sass/pull/200/files.

@iMoritz, would be a treat if we get #37 in middleware's vNext as well (before or after v3 changes, doesn't matter; as it will probably require equal amount of effort)

**Comment by jerone** [comment]
[**@am11**](https://github.com/am11) commented on [6 mei 2015 23:06 CEST](https://github.com/sass/node-sass-middleware/issues/31#issuecomment-99609938 "2015-05-06T21:06:39Z - Replied by Github Comment Enhancer"):
> [...] Otherwise, anyone can start a PR [...]

I'm sorry, I have moved on to other projects.

**Comment by iMoritz** [comment]
I just implemented node-sass v3 support in my fork: https://github.com/iMoritz/node-sass-middleware/commit/1ea16c12e75a3d85487ea12d2c10c6463425b6e5 

@am11 
Just waiting for #40 to get merged because my v3 support is built on top of it
I will go on #37 after node-sass v3 is implemented

**Comment by bumxu** [comment]
A few remarks:
- Option `imagePath` is no longer supported by `node-sass` and `libsass`.
- Maybe error handling should use `err.file` when available (distinct of `null` or `"stdin"`), and format output expecting more than one line (backtrace).

See bumxu@ddd0ec1b83899c8d01c3938f14b7598549e7dcb1 for details.

**Comment by am11** [comment]
@iMoritz, @bumxu, thank you guys for showing interest. Feel free to start a new PR. You guys can collaborate in a single PR (one of you will need to cherrypick other's commits).
@bumxu, this is true. There are couple of options obsoleted. This would require revamping most of the middleware code (both middleware.js and test/).

**Comment by bumxu** [comment]
Maybe in case of compilation error, it would be more correct to call `error` function (that I deleted by mistake), and therefore to `next(err)` instead of end connection with 500.
What do you think? :confused:
