### ISSUE TITLE
SourceMap

### ISSUE THREAD

**Issue by jerone** [sass/node-sass-middleware#33]
Any plans in adding [`node-sass`](https://github.com/sass/node-sass) [sourceMap](https://github.com/sass/node-sass#sourcemap) feature?

**Comment by am11** [comment]
@jerone, would you like to take a stab at it?  :)

**Comment by jerone** [comment]
I would, but can't :( I really don't have time for it in the next month.
I would however use the benefits from this, so if someone else would give it a try...

**Comment by iMoritz** [comment]
fixed in #44

**Comment by am11** [comment]
Arrived with v0.8. :rocket:
