### ISSUE TITLE
Installation fails at downloading bindings

### ISSUE THREAD

**Issue by Dragowynd** [sass/node-sass-middleware#35]
I tried installing node-sass-middleware but it fails to download the bindings and crashes because node-gyp is not installed.
![Log](https://cloud.githubusercontent.com/assets/2495581/6634899/72fe9de6-c95f-11e4-88c0-8770f0743476.png)
I tried installing it with Node.js 0.12.0 with npm 2.5.1 and IO.js 1.5.1 and npm 2.7.1

**Comment by xzyfer** [comment]
Hi Jonathan

This a known issue. Please use node 0.10 or io.js <=1.2. Other runtimes are
supported in node-sass@3.0.0-pre.

**Comment by Dragowynd** [comment]
Hi Michael,
thanks for the information. I will create a workaround myself for the time being :)
