### ISSUE TITLE
Compiles only .scss no .sass files

### ISSUE THREAD

**Issue by iMoritz** [sass/node-sass-middleware#36]
node-sass-middleware looks only for .scss files but I prefer using sass without any braces or semicolons

**Comment by jerone** [comment]
[Node-sass](https://github.com/sass/node-sass) indeed supports the `.sass` extension; https://github.com/sass/node-sass/blob/1e075931475cf2ddbbaf1e421b223a01bc57ed50/bin/node-sass#L92

This is not supported right now.

**Comment by am11** [comment]
Seems like this is related https://github.com/sass/node-sass-middleware/pull/20.
It just needs a rebase.

**Comment by iMoritz** [comment]
Fixed in #43

**Comment by am11** [comment]
Arrived with v0.7. 
Thanks @iMoritz! :tada:
