### ISSUE TITLE
Using the middleware doesn't cause files with imports that changed to be recompiled

### ISSUE THREAD

**Issue by ilanbiala** [sass/node-sass-middleware#5]
I have a file that imports another file, something like this:

```
@import '_fonts';

input {

}
```

The _fonts file will change, but the middleware will not recompile the file because the file itself didn't change, even though the compiled file would change.

**Comment by Bumxu** [comment]
Hello,
I'm having the same problem, was this issue fixed?

From what I could see ```imports``` object in ```checkImport``` is always empty.
