### ISSUE TITLE
New server run doesn't create new css (force=false)

### ISSUE THREAD

**Issue by gkorland** [sass/node-sass-middleware#54]
It seems like when  setting force=false a new build is created only when restarting the server.
But, in lately when we restart our express server (on windows) no new build is created until the previous css is deleted.

**Comment by am11** [comment]
This is an intentional behaviour. Unless the source (`.scss`/`.sass`) has changed it does not recompile the existing CSS. If you want it to recompile it overriding this policy, set `options.force` to true.

**Comment by gkorland** [comment]
The thing is that the source has changed.

**Comment by am11** [comment]
Can you please try with the latest master: `npm install sass/node-sass-middleware` and help us figuring out the steps to repro? I cannot replicate this behavior locally with two `.scss` files importing each other. Thanks.

**Comment by gkorland** [comment]
We're using the latest version. We could't recreate it locally. 
It only happens when we deploy a new version in production. (Azure Web App)

**Comment by am11** [comment]
Alright, I will play with it later this week to see if i can reproduce it somehow. Unless someone else beat me to it isolating the steps to repro. :)

**Comment by gkorland** [comment]
OK, I found it, sorry for the trouble. 
A week ago we configured the IIS (Azure Web App is using iisnode) to serve all the static content including the css files, which means we never let the middleware to opportunity to recompile the file. 

Is there a way to force the middleware to compile the file on server load and not on the GET call?
