### ISSUE TITLE
race condition

### ISSUE THREAD

**Issue by jimcftr** [sass/node-sass-middleware#62]
Basically the "options" object which gets passed into node-sass, is modified by node-sass, but it's reused as a module global within node-sass-middleware.
So if more than one request is in flight, they end up stomping on each other and havoc ensues, including the callbacks getting jumbled (which manifests itself as res.sendHeader() throwing errors about the headers already been sent).

I cloned locally and made a simple fix to just clone the options object for each request. It works and gets past the problem. Could one of the maintainers review and see if you want to take this, or do a similar fix?

diff --git a/middleware.js b/middleware.js
index 36be2ed..c31356f 100644
--- a/middleware.js
+++ b/middleware.js
@@ -5,6 +5,7 @@ var sass = require('node-sass'),
     url = require('url'),
     dirname = require('path').dirname,
     mkdirp = require('mkdirp'),
+    extend = require('extend'),
     join = require('path').join;
 
 var imports = {};
@@ -95,7 +96,7 @@ module.exports = function(options) {
   };
 
   // Middleware
-  return function sass(req, res, next) {
+  function sass_middleware(options, req, res, next) {
     if (req.method != 'GET' && req.method != 'HEAD') {
       return next();
     }
@@ -282,6 +283,10 @@ module.exports = function(options) {
       });
     });
   }
+
+  return function(req, res, next) {
+    return sass_middleware(extend({}, options), req, res, next);
+  }
 };
 
 /**
diff --git a/package.json b/package.json
index 74ca39f..f9a4b31 100644
--- a/package.json
+++ b/package.json
@@ -30,6 +30,7 @@
     "node": ">=0.10.0"
   },
   "dependencies": {
+    "extend": "^3.0.0",
     "mkdirp": "^0.5.1",
     "node-sass": "^3.3.2"
   },

**Comment by lxndr** [comment]
I can confirm it. This happens to me when I use Firefox. Please, fix it.

**Comment by am11** [comment]
x-ref #61.

**Comment by am11** [comment]
Fixed by #61 and landed in [v0.9.7](https://github.com/sass/node-sass-middleware/releases/tag/v0.9.7).
Thanks for reporting this issue and for the good write up as well! :)
