### ISSUE TITLE
node-sass download

### ISSUE THREAD

**Issue by CrackerakiUA** [sass/node-sass-middleware#72]
I have installed latest node '6.0.0' and when i try to install this i see `Cannot download "https://github.com/sass/node-sass/releases/download/v3.6.0/win32-x64-48_binding.node":
` and in the [node-sass](https://github.com/sass/node-sass/releases) there is no -48 version.

**Comment by am11** [comment]
This issue is being tracked in binaries repo: https://github.com/sass/node-sass-binaries/issues/128.
In the meanwhile, if you have Visual Studio or VC Build Tools 2015 installed, you can try:

```cmd
:: set environment variable to force compile the binary locally
SET SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=1

:: then install the package
npm install
```

**Comment by CrackerakiUA** [comment]
i am using terminal from git

**Comment by am11** [comment]
node-sass v3.7.0 supports node.js v6
 `npm i node-sass@3.7.0`
