### ISSUE TITLE
Update to node-sass 3.7.0

### ISSUE THREAD

**Issue by visualcookie** [sass/node-sass-middleware#74]
Hi,

is there an update coming to node-sass 3.7.0? Would be pretty amazing! :)

**Comment by am11** [comment]
Hi, if you `npm i node-sass-middleware` in a folder, it will install node-sass v3.7.0. Note that in our package.json, we have node-sass as a [caret dependency](https://docs.npmjs.com/cli/update#caret-dependencies) (prefixed with `^`), which installs the latest minor version. (so ^3.4 means `3.<latest-minor-and-patch-version>`). This way we do not need to update dependencies version, unless the major version changes, which usually brings some breaking changes.

**Comment by visualcookie** [comment]
Oh, awesome. Didn't knew that yet. Thank you. :+1:
