### ISSUE TITLE
Phonegap

### ISSUE THREAD

**Issue by CrackerakiUA** [sass/node-sass-middleware#77]
How do we use it insde an phonegap app? i was thinking if we make small node app which will only run sass-middleware that will generate index.css but it's not working. Do we have something like generate code each 1 second or do we have other way to do this?

**Comment by nschonni** [comment]
Sorry, from the README:
> Connect/Express middleware for node-sass.

Unless you're running one of those midtiers inside your application it won't work. node-sass also needs to be running no Node, not on a native javascript environment.
