### ISSUE TITLE
vendor/darwin-x64-46/binding.node Missing After npm install

### ISSUE THREAD

**Issue by aconfee** [sass/node-sass-middleware#79]
Hello,

I recently deleted all of my node_modules for a particular project off of git in order to reduce it's size (no surprises here), and after running npm install on my local directory, I was no longer able to run my application because node_modules/node-sass-middleware/node_modules/node-sass/vendor cannot be found -- and it is in fact missing. 

I originally installed this package with the Express generator. 

Any ideas? I'd be happy to provide more detail or set up a time to track this issue.

Thanks!
Adam

**Comment by saper** [comment]
Did you upgrade your npm from 2 to 3 in the meantime? Any node upgrades? Does `npm install node-sass` Aldonę work?

**Comment by aconfee** [comment]
Thanks for responding! I haven't done any upgrades since starting this project. I'm using node v. 4.4.5 and npm v. 2.15.5. 

It looks like npm install node-sass works fine -- the vendor folder is generated. 

However, I noticed a couple things: installing node-sass-middleware if node-sass is already installed produces a different directory structure. node-sass won't be nested in node-sass-middleware if it already exists before installing the middleware.

node-sass-middleware still does not produce the vendor folder even when installed clean (I deleted node-sass-middleware and node-sass and tried installing node-sass-middleware again).

**Comment by xzyfer** [comment]
> However, I noticed a couple things: installing node-sass-middleware if node-sass is already installed produces a different directory structure. 

This an npm implementation detail. It wont affect anything since `require` will know where to look.

> node-sass-middleware still does not produce the vendor folder even when installed clean

npm only runs the install scripts of direct dependencies, not their dependencies. This is a performance optimization in npm but unfortunately causes this issue. If you already have npm folder in your node_modules it won't check to see if you have the correct vendor binary.

**Comment by xzyfer** [comment]
There isn't anything we can do here unfortunately. Running the following will fix almost all node-sass (and all native module) problems.

```
npm rebuild node-sass
```

**Comment by aconfee** [comment]
Looks like that doesn't help :/ I'll dig a bit deeper to see what is trying to find the vendor folder in that path specifically.
