### ISSUE TITLE
prefix ignored when running

### ISSUE THREAD

**Issue by silverlight513** [sass/node-sass-middleware#88]
I have two calls for css files in my index.html, one uses the prefix the other does not. Both css files are picked up by sass-middleware instead of just the one with the prefix.

My config looks like this:
```
{
    src: path.join(__dirname, './client/sass'),
    dest: path.join(__dirname, './dist'),
    debug: true,
    outputStyle: 'compressed',
    prefix:  '/css'
}
```

I have links in my html that look like:
```
<link rel="stylesheet" href="/css/app.css" type="text/css">
<link rel="stylesheet" href="/outdated-browser/outdatedbrowser.min.css" type="text/css">
```

I am aware that I can just put the express.static method for outdated browser above the sass middleware and it won't get picked up by the middleware but the middleware shouldn't be picking it up anyway.

**Comment by am11** [comment]
Admittedly, the prefix mechanics are bit tricky to get the middleware setup right. See this conversation https://github.com/sass/node-sass-middleware/issues/49#issuecomment-264976499 which points to an example project. I hope that will help.
