### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by willybeans** [sass/node-sass-middleware#92]
Currently running on mac osx 10.6 snow leopard. first came across errors which seemed to be from not having xcode. tried to install xcode command line tools which still resulted in problems, and then installed xcode 3.2, the last compatible version for this OS, and here are my most current issues: https://gist.github.com/willybeans/45d5519db4e3df7bf19f231c38b4467e

**Comment by am11** [comment]
Hi @willybeans, this issue belongs to upstream node-sass repo and is duplicate of https://github.com/sass/node-sass/issues/1160.

Nonetheless, can you try upgrading node.js to latest stable v6.9 from https://nodejs.org/en/download to see if it solves the problem?

Thanks.

**Comment by willybeans** [comment]
that did not fix it. my apologies for the duplicate. i will go through the trouble shooting and come back with more concrete information.
