### ISSUE TITLE
Caching ?

### ISSUE THREAD

**Issue by MentalGear** [sass/node-sass-middleware#99]
Just wondering what sort of cache handling is done by this plugin ?
Are stylesheets for every page request regenerated, or only once on server start ?

**Comment by am11** [comment]
We do not cache the stylesheet results at all, but instead rely on 'modified timestamp' of `.css` vs. `.scss`/`.sass`.

We *definitely* compile if either of following conditions are met:
* options.force is set
* the target CSS does not exist
* the target CSS exists, and `sass_source_modified_time` > `css_target_modified_time`, then recompile

Otherwise (after asserting all the implementation details), we skip the compilation step and simply invoke the caller's next middleware -- which in most cases is either (postcss-based) minifier or static files middleware.

**Comment by MentalGear** [comment]
Mh... and the sass timestamp is copied right over from the original css file ?
Otherwise I would assume the sass timestamp could always differ because of the time it takes for the file to be converted.

Also, I noticed that the middleware seems to check any html files for external files ( in debug mode .js and .jpg files also pop up ), and then look into those folders, which I find somewhat peculiar.

For example, given the following folder structure
/stylesheets
--- /sass
--- /compiled_css/
----/third_party_library_css

Yet, when set to
 sassMiddleware({
        /* Options */
        root: __dirname + "/public/stylesheets",
        src: "/sass",
        dest: "/css_compiled",

I still see in the debug that the sassMiddleware is looking for files like "selectbox.js.min" to convert, even though those are, besides scripts, not even in the src folder.
Shouldn't the library be only looking in the source folder, instead of into all the path defined in all html files?

Also, is there a way to skip all files but sass files ?

**Comment by am11** [comment]
> sass timestamp is copied right over from the original css file ?

The modified timestamp is set by OS when user or application modifies some file, we read the file metadata via node.js standard file-system API (`mtime` in `fstat` object: https://nodejs.org/api/fs.html#fs_class_fs_stats).

>the debug that the sassMiddleware is looking for files like "selectbox.js.min" to convert

Nope, in debug, we just log a message that our middleware has 'seen' this request, but skip to the `next()` one right away, if the requested asset is a non-css file.

> Also, is there a way to skip all files but sass files?

The concept of middleware is that the server (`express.js` et al.) passes through the request to the middleware chain; the first middleware calls the second one, second calls the third and so on. If some middleware wants to handle the request, it will do so and either:

* pass the control to the next one by calling `next()` function injected by the server app
* respond success (200) or error (404 etc.) and terminate the middleware pipe.

The middleware is configured by the consumer and `next()` follows the order the user has specified:

e.g.

```javascript
var server = require('express')();
var sassMiddleware = require('node-sass-middleware');
var postcssMiddleware = require('postcss-middleware');

server
  .use ( sassMiddleware ( sassMiddlewareOptions ) )        // this middleware will be called first
  .use ( postcssMiddleware ( postcssMiddlewareOptions ) )  // this will be called when previous
                                                           // one invokes next()
/* and so on */
  ;
```
